fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,15 +41,18 @@ jobs:
       run: npm run cy:run:cov
 
     - name: Cov merge
+      if: success() || failure() # always run even if the previous step fails
       run: npm run cov:merge && npm run cov:fin
 
     - name: Archive code coverage results
+      if: success() || failure() # always run even if the previous step fails
       uses: actions/upload-artifact@v3
       with:
         name: code-coverage-report
         path: ./reports/coverage-full-total/lcov-report/
 
     - name: Monitor coverage
+      if: success() || failure() # always run even if the previous step fails
       uses: slavcodev/coverage-monitor-action@v1
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -61,6 +64,7 @@ jobs:
       with:
         report_paths: '**/reports/jest/*.xml'
         check_name: 'Jest Test Report'
+        detailed_summary: true
 
     - name: Publish Cy Test Report
       uses: mikepenz/action-junit-report@v3
@@ -68,6 +72,7 @@ jobs:
       with:
         report_paths: '**/reports/cypress/*.xml'
         check_name: 'Cy Test Report'
+        detailed_summary: true
 
 
     - name: Publish
