[patch] added tests reports (#8)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,35 +41,67 @@ jobs:
       run: npm run cy:run:cov
 
     - name: Cov merge
+      if: success() || failure() # always run even if the previous step fails
       run: npm run cov:merge && npm run cov:fin
 
     - name: Archive code coverage results
+      if: success() || failure() # always run even if the previous step fails
       uses: actions/upload-artifact@v3
       with:
         name: code-coverage-report
         path: ./reports/coverage-full-total/lcov-report/
 
     - name: Monitor coverage
+      if: success() || failure() # always run even if the previous step fails
       uses: slavcodev/coverage-monitor-action@v1
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         coverage_path: "reports/coverage-full-total/clover.xml"
 
+    - name: Publish Jest Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/reports/jest/*.xml'
+        check_name: 'Jest Test Report'
+        detailed_summary: true
+
+    - name: Publish Cy Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/reports/cypress/*.xml'
+        check_name: 'Cy Test Report'
+        detailed_summary: true
+
+
     - name: Publish
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+        commitmsg: ${{ github.event.head_commit.message }}
       run: |
+        # if: github.ref == 'refs/heads/main'
         branch=${{ github.ref }}
         echo "Branch: $branch" 
-        
-        gitmsg=$(git log -1 --pretty=%B)
+
         msg2=${{ github.event.commits[0].message }}
         msg=${{ github.event.head_commit.message }}
         echo "Commit: $msg" 
         echo "Commit2: $msg2" 
+
+        gitmsg=${{ env.commitmsg }}
+
         echo "gitmsg: $gitmsg" 
         
         if [[ "$gitmsg" =~ "[patch]" ]]; then
+          echo "publish patch"
+          npm run publish:patch
+          git push --tags
+          exit 0
+        fi 
+        
+        if [[ "$gitmsg" =~ "[fix]" ]]; then
           echo "publish patch"
           npm run publish:patch
           git push --tags
@@ -90,6 +122,6 @@ jobs:
           exit 0
         fi
         
-        echo "publishing alpha, for other commit message should contain [minor], [major] or [patch]"
+        echo "publishing alpha, for other commit message should contain [minor], [major] or [patch]/[fix]"
         npm run publish:alpha
         git push --tags
